# Generated by Django 5.1.2 on 2024-10-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0008_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='profileOne',
            new_name='profile1',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='profileTwo',
            new_name='profile2',
        ),
        migrations.AddField(
            model_name='friend',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
